language: ruby
rvm:
  - 2.2
branches:
  only:
    - gh-pages
    - /^.*$/
notifications:
  irc:
    channels:
      - "chat.freenode.net#accumulo"
    use_notice: true
    on_success: change
    on_failure: always
    template:
      - "%{result} %{repository_slug} %{branch} (%{build_url}): %{message}"
cache: bundler
script: ./_devtools/cibuild
