# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apache Accumulo™
email: dev@accumulo.apache.org
description: > # this means to ignore newlines until "baseurl:"
  The Apache Accumulo™ sorted, distributed key/value store is a robust, scalable,
  high performance data storage and retrieval system.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://accumulo.apache.org" # the base hostname & protocol for your site
twitter_username: ApacheAccumulo
github_username:  apache/accumulo
repository: apache/accumulo
exclude: [vendor]
latest_minor_release: 1.7

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "skeleton"

whitelist: [jekyll-redirect-from]
gems: [jekyll-redirect-from]
