# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apache Accumulo™
email: dev@accumulo.apache.org
description: > # this means to ignore newlines until "baseurl:"
  The Apache Accumulo™ sorted, distributed key/value store is a robust, scalable,
  high performance data storage and retrieval system.
baseurl: "/accumulo" # the subpath of your site, e.g. /blog
url: "https://accumulo.apache.org" # the base hostname & protocol for your site
twitter_username: ApacheAccumulo
exclude: [vendor]
latest_minor_release: 1.8
num_home_posts: 5

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_posts/blog"
      type: "posts"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "_posts/release"
      type: "posts"
    values:
      layout: "release"
      category: "release"
      permalink: "/:categories/:title/"
whitelist: [jekyll-redirect-from]
gems: [jekyll-redirect-from]
